name: Deploy Lambda

on:
  push:
    branches: [main, master]
    paths:
      - 'server/**'
      - '.github/workflows/**'

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: server

    steps:
    - uses: actions/checkout@v4

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
        aws-region: 'us-east-1'
        audience: sts.amazonaws.com

    - name: Install dependencies
      run: |
        pip install -r requirements.txt -t .

    - name: Package Lambda
      run: |
        zip -r lambda.zip ./*

    - name: Deploy to Lambda
      run: |
        aws lambda update-function-code \
          --function-name contact-form-handler \
          --zip-file fileb://lambda.zip